#ifndef MSH_DEP_ALL_DEFINES_H
#define MSH_DEP_ALL_DEFINES_H

#define SMARTBUFFER_CUSTOM
#define SMARTBUFFER_CHAR index8
#define SMARTBUFFER_LEN_T index64
#define SMARTBUFFER_BOOL_T bool
#define SMARTBUFFER_TRUE true
#define SMARTBUFFER_FALSE false

#endif
